### ISSUE TITLE
Bug: User Interface

### ISSUE THREAD

**Issue by ClemensBeck** [slub/3d-viewer#8]
* [x] Check and Fix User Interface Bug 
Information: 
Windows 10, Resolution 1920x1080, Chrome 105.0.5195.127 
Windows 10, Resolution 1920x1080, Firefox 105.0.1 
![User Interface](https://user-images.githubusercontent.com/110522037/194051489-188c64ba-6ec5-41e5-bdbb-08e3d173f38c.JPG)

**Comment by beatrycze-volk** [comment]
It should work now. I have tested for Chrome in resolution 1920x1080. Could you verify it?
